"""Matched selectors trained only on out-of-fold candidate predictions."""
from __future__ import annotations
from pathlib import Path
from dataclasses import replace
import json
import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.special import expit
from .io import write_json,read_json,write_table,digest,atomic_npz
from .training import TrainSpec,train_predictor,predict_run

GENERIC_FEATURES=["candidate_confidence","joint_marginal_gap","entropy","specificity"]
PROVENANCE_FEATURES=["n_sources","has_documentary","source_age_days","missing_premises","source_conflicts","unknown_mass"]
# This is an allowlist, not 'all columns other than y'. References can never be inputs.


class SoftLogistic:
    def __init__(self,l2=.01):self.l2=l2
    def fit(self,x,y):
        x=np.asarray(x,float);y=np.asarray(y,float)
        if x.ndim!=2 or y.shape!=(len(x),):raise ValueError("Invalid selector shapes")
        if not np.isfinite(x).all() or not np.isfinite(y).all():raise ValueError("Nonfinite selector input")
        if not ((0<=y)&(y<=1)).all():raise ValueError("Invalid support targets")
        self.mean=x.mean(0);self.std=x.std(0).clip(1e-6);z=(x-self.mean)/self.std
        z=np.column_stack([np.ones(len(z)),z])
        def fun(w):
            p=z@w;err=expit(p)-y;reg=w.copy();reg[0]=0
            return np.mean(np.logaddexp(0,p)-y*p)+self.l2*np.sum(reg**2)/2,z.T@err/len(z)+self.l2*reg
        result=minimize(fun,np.zeros(z.shape[1]),jac=True,method="L-BFGS-B",options={"maxiter":1000})
        if not result.success:raise RuntimeError(f"Selector optimisation failed: {result.message}")
        self.weights=result.x;return self
    def logits(self,x):
        z=(np.asarray(x,float)-self.mean)/self.std
        return np.column_stack([np.ones(len(z)),z])@self.weights
    def predict(self,x):return expit(self.logits(x))
    def save(self,path,features,provenance):
        write_json(path,{"kind":"soft_logistic","l2":self.l2,"mean":self.mean,"std":self.std,"weights":self.weights,
                         "features":features,"provenance":provenance})
    @classmethod
    def load(cls,path):
        a=read_json(path);m=cls(a["l2"]);m.mean=np.array(a["mean"]);m.std=np.array(a["std"]);m.weights=np.array(a["weights"])
        return m,a["features"]


def validate_oof_ledger(df):
    required={"record_id","group_id","fold","training_group_ids","early_stop_group_ids","candidate_id","split"}
    if required-set(df):raise ValueError(f"OOF ledger missing {required-set(df)}")
    if not df.split.eq("fit").all():raise ValueError("Selector fitting requires only fit-partition OOF rows")
    for row in df.itertuples():
        train=json.loads(row.training_group_ids);val=json.loads(row.early_stop_group_ids)
        if row.group_id in train or row.group_id in val:raise ValueError("Candidate was generated by a model exposed to its group")
    if df.candidate_id.duplicated().any():raise ValueError("Duplicate OOF candidate IDs")
    return True


def oof_predictors(records,targets,spec,root,features,folds=4,device=None):
    fit=records[records.split=="fit"].copy();groups=np.array(sorted(fit.group_id.unique()),dtype=str)
    if len(groups)<folds+3:raise ValueError("Too few fitting groups for OOF plus inner validation")
    np.random.default_rng(spec.seed).shuffle(groups);parts=np.array_split(groups,folds);ledger=[];predictions=[]
    for k,held in enumerate(parts):
        available=np.setdiff1d(groups,held);np.random.default_rng(spec.seed+100+k).shuffle(available)
        nv=max(1,int(round(.2*len(available))));vg=available[:nv];tg=available[nv:]
        tr=fit[fit.group_id.isin(tg)];va=fit[fit.group_id.isin(vg)];ho=fit[fit.group_id.isin(held)]
        run=Path(root)/f"fold_{k}";foldspec=replace(spec)
        train_predictor(fit,targets,foldspec,run,Path(features)/f"fold{k}",fit_ids=list(tr.record_id),val_ids=list(va.record_id),device=device)
        pred=predict_run(run,ho,targets,Path(features)/f"fold{k}",device=device)
        atomic_npz(run/"heldout_predictions.npz",**pred)
        p=expit(pred["logits"]);j=p.argmax(1)
        for idx,row in enumerate(ho.itertuples()):
            label=targets["schema"]["labels"][j[idx]]
            cid=digest({"record":row.record_id,"label":label,"run":spec.run_id,"fold":k})[:24]
            ledger.append({"record_id":row.record_id,"group_id":row.group_id,"split":"fit","fold":k,"candidate_id":cid,
              "training_group_ids":json.dumps(sorted(tg)),"early_stop_group_ids":json.dumps(sorted(vg)),"label":label,
              "candidate_confidence":float(p[idx,j[idx]]),"entropy":float(-(p[idx]*np.log(p[idx]+1e-8)+(1-p[idx])*np.log(1-p[idx]+1e-8)).mean()),
              "annotation_endorsement":float(pred["y"][idx,j[idx]]),"annotation_observed":bool(pred["mask"][idx,j[idx]]),
              "joint_marginal_gap":0.0,"specificity":len(json.loads(label))})
        predictions.append(pred)
    result=pd.DataFrame(ledger);validate_oof_ledger(result);write_table(Path(root)/"oof_ledger.csv",result)
    return result


def train_selectors(oof_candidates,ratings,out,*,label_kind="independent_claim_rubric"):
    validate_oof_ledger(oof_candidates)
    if label_kind=="independent_claim_rubric":
        if ratings is None:raise ValueError("Claim-support selectors require independent ratings; expert visual endorsement is not a substitute")
        if ratings.candidate_id.duplicated().any():raise ValueError("Adjudicate duplicate ratings first")
        df=oof_candidates.merge(ratings[["candidate_id","support_status"]],on="candidate_id",validate="one_to_one",how="left")
        if df.support_status.isna().any():raise ValueError("Missing independently adjudicated OOF claim ratings")
        if not df.support_status.isin(["supported","contradicted","unverifiable","noninformative"]).all():raise ValueError("Unexpected support status")
        df=df[df.support_status.ne("noninformative")].copy()
        if df.empty:raise ValueError("No informative rated fitting candidates")
        y=df.support_status.eq("supported").to_numpy(float)
    elif label_kind=="expert_visual_endorsement_foundation_only":
        df=oof_candidates[oof_candidates.annotation_observed.astype(str).str.lower().isin(["true","1"])].copy();y=df.annotation_endorsement.to_numpy(float)
    else:raise ValueError("Unknown selector target")
    out=Path(out);out.mkdir(parents=True,exist_ok=True);result={}
    for name,features in {"generic":GENERIC_FEATURES,"pcsi":GENERIC_FEATURES+PROVENANCE_FEATURES}.items():
        if set(features)-set(df):raise ValueError(f"Missing INFERENCE features for {name}: {set(features)-set(df)}")
        x=df[features].to_numpy(float);model=SoftLogistic().fit(x,y)
        model.save(out/f"{name}.json",features,{"target":label_kind,"oof_hash":digest(df.to_dict("records"))})
        result[name]=model
    return result


def choose_threshold(scores,eligible,target=.8,weights=None):
    scores=np.asarray(scores,float);eligible=np.asarray(eligible,bool)
    w=np.ones(len(scores)) if weights is None else np.asarray(weights,float)
    if len(scores)==0 or w.sum()<=0:raise ValueError("Empty validation operating point")
    if not np.isfinite(scores).all():raise ValueError("Nonfinite selection score")
    options=np.r_[1.000001,np.unique(scores[eligible])]
    cover=np.array([w[eligible&(scores>=t)].sum()/w.sum() for t in options])
    # Closest achievable point. Ties favour higher threshold, not a reference-informed tie break.
    error=np.abs(cover-target);best=np.flatnonzero(np.isclose(error,error.min()))
    idx=best[np.argmax(options[best])]
    return {"threshold":float(options[idx]),"target_coverage":target,"validation_coverage":float(cover[idx]),
            "maximum_eligible_coverage":float(w[eligible].sum()/w.sum()),"ties":"include_all_at_threshold"}


class SoftMLP:
    """Optional fixed-capacity soft-label selector; architecture/epochs fixed before test.
    Serialization is JSON weights rather than untrusted pickle.
    """
    def __init__(self,hidden=32,epochs=200,lr=.001,seed=0):
        self.hidden,self.epochs,self.lr,self.seed=hidden,epochs,lr,seed
    def fit(self,x,y):
        import torch
        from torch import nn
        torch.manual_seed(self.seed)
        x=np.asarray(x,float);y=np.asarray(y,float)
        if not np.isfinite(x).all() or not ((0<=y)&(y<=1)).all():raise ValueError("Invalid selector inputs")
        self.mean=x.mean(0);self.std=x.std(0).clip(1e-6)
        self.model=nn.Sequential(nn.Linear(x.shape[1],self.hidden),nn.ReLU(),nn.Linear(self.hidden,1))
        opt=torch.optim.AdamW(self.model.parameters(),lr=self.lr,weight_decay=.01)
        xx=torch.tensor((x-self.mean)/self.std,dtype=torch.float32);yy=torch.tensor(y[:,None],dtype=torch.float32)
        for _ in range(self.epochs):
            opt.zero_grad();loss=nn.functional.binary_cross_entropy_with_logits(self.model(xx),yy);loss.backward();opt.step()
        return self
    def logits(self,x):
        import torch
        self.model.eval()
        with torch.inference_mode():return self.model(torch.tensor((np.asarray(x)-self.mean)/self.std,dtype=torch.float32)).numpy().ravel()
    def predict(self,x):return expit(self.logits(x))
    def save(self,path,features,provenance):
        write_json(path,{"kind":"soft_mlp","hidden":self.hidden,"epochs":self.epochs,"lr":self.lr,"seed":self.seed,
                         "mean":self.mean,"std":self.std,"features":features,"provenance":provenance,
                         "weights":{k:v.detach().numpy() for k,v in self.model.state_dict().items()}})
    @classmethod
    def load(cls,path):
        import torch
        from torch import nn
        a=read_json(path);m=cls(a["hidden"],a["epochs"],a["lr"],a["seed"])
        m.mean=np.array(a["mean"]);m.std=np.array(a["std"])
        m.model=nn.Sequential(nn.Linear(len(m.mean),m.hidden),nn.ReLU(),nn.Linear(m.hidden,1))
        m.model.load_state_dict({k:torch.tensor(v,dtype=torch.float32) for k,v in a["weights"].items()})
        return m,a["features"]


def load_selector(path):
    return (SoftMLP if read_json(path)["kind"]=="soft_mlp" else SoftLogistic).load(path)
